info:
  description: '{"en":"GmvMaxCampaignInfo","zh":"GmvMaxCampaignInfo"}'
  title: '{"en":"GmvMaxCampaignInfo","zh":"GmvMaxCampaignInfo"}'
  version: 1.0.0
openapi: 3.0.1
paths:
  /campaign/gmv_max/info/:
    get:
      operationId: Campaign Gmv_max Info
      parameters:
      - description: ''
        in: query
        name: advertiser_id
        required: true
        schema:
          nullable: false
          type: string
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-convert:
          - int64(%s)
          x-open-source: $.http.query.advertiser_id
        x-open-field-id: 1
      - description: ''
        in: query
        name: campaign_id
        required: true
        schema:
          nullable: false
          type: string
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-convert:
          - int64(%s)
          x-open-source: $.http.query.campaign_id
        x-open-field-id: 2
      - description: Authorized access token. For details, see [Authentication](https://ads.tiktok.com/marketing_api/docs?id=1738373164380162).
        in: query
        name: Access-Token
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Response code. For the complete list of response
                      codes and descriptions, see [Appendix - Return Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                      Will be shown only if it is an error request.
                    format: int64
                    nullable: true
                    type: integer
                    x-open-allow-strlist: false
                    x-open-field-id: 4
                  data:
                    description: Returned data. The response for the SDK can be checked
                      in the document for the API given in the description.
                    nullable: true
                    properties: {}
                    type: object
                    x-open-allow-strlist: false
                    x-open-field-id: 1
                    x-open-source: $.rpc.output.data
                  message:
                    description: Response message. For details, see [Appendix - Return
                      Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 3
                  request_id:
                    description: The log ID of a request, which uniquely identifies
                      the request.
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 2
                type: object
                x-open-allow-strlist: false
          description: OK
      summary: Get GMV Max campaign info [Smart Plus GMV Max Campaign Info](https://business-api.tiktok.com/portal/docs?id=1822000968821762)
      tags:
      - Campaign Creation
      x-open-allowlist: {}
      x-open-denylist: {}
      x-open-rules:
        base_rule: null
        extra_rule:
          base_source: []
          http_query_source: []
          http_source:
          - name: advertiser_id
            required: true
            source: $.http.query.advertiser_id
            type: number
          - name: campaign_id
            required: true
            source: $.http.query.campaign_id
            type: number
          - children:
            - name: app_id
              required: false
              source: $.http.query.context_info.app_id
              type: number
            - name: core_user_id
              required: false
              source: $.http.query.context_info.core_user_id
              type: number
            - name: developer_id
              required: false
              source: $.http.query.context_info.developer_id
              type: number
            - name: x_forwarded_for
              required: false
              source: $.http.query.context_info.x_forwarded_for
              type: string
            - name: x_real_ip
              required: false
              source: $.http.query.context_info.x_real_ip
              type: string
            - name: user_agent
              required: false
              source: $.http.query.context_info.user_agent
              type: string
            - name: referer
              required: false
              source: $.http.query.context_info.referer
              type: string
            is_expand: false
            name: context_info
            required: false
            source: $.http.query.context_info
            type: object
        plugins:
          after_response: []
          before_request: []
        request_query_rule: null
        request_rule:
          advertiser_id: $.http.query.advertiser_id
          campaign_id: $.http.query.campaign_id
          context_info: $.http.query.context_info
        response_cookie: []
        response_header: []
        response_rule:
          advertiser_id: $.rpc.output.gmv_max_data.advertiser_id
          affiliate_posts_enabled: $.rpc.output.gmv_max_data.shop_aca_mode
          age_groups: $.rpc.output.gmv_max_data.age
          auto_budget_enabled: $.rpc.output.gmv_max_data.auto_budget_enabled
          budget: $.rpc.output.gmv_max_data.budget
          campaign_custom_anchor_video_id: $.rpc.output.gmv_max_data.custom_anchor_video_ref_id
          campaign_id: $.rpc.output.gmv_max_data.campaign_id
          campaign_name: $.rpc.output.gmv_max_data.campaign_name
          custom_anchor_video_list[][]:
          - identity_info[]:
            - identity_authorized_bc_id: $.rpc.output.gmv_max_data.custom_anchor_video_list[].identity_info.identity_authorized_bc_id
              identity_authorized_shop_id: $.rpc.output.gmv_max_data.custom_anchor_video_list[].identity_info.identity_authorized_shop_id
              identity_id: $.rpc.output.gmv_max_data.custom_anchor_video_list[].identity_info.identity_id
              identity_type: $.rpc.output.gmv_max_data.custom_anchor_video_list[].identity_info.identity_type
              store_id: $.rpc.output.gmv_max_data.custom_anchor_video_list[].identity_info.store_id
            item_id: $.rpc.output.gmv_max_data.custom_anchor_video_list[].item_id
            spu_id_list: $.rpc.output.gmv_max_data.custom_anchor_video_list[].spu_id_list
          deep_bid_type: $.rpc.output.gmv_max_data.deep_bid_type
          identity_list: $.rpc.output.gmv_max_data.identity_list
          item_group_ids: $.rpc.output.gmv_max_data.spu_list
          item_list[][]:
          - identity_info[]:
            - identity_authorized_bc_id: $.rpc.output.gmv_max_data.shop_item_list[].identity_info.identity_authorized_bc_id
              identity_authorized_shop_id: $.rpc.output.gmv_max_data.shop_item_list[].identity_info.identity_authorized_shop_id
              identity_id: $.rpc.output.gmv_max_data.shop_item_list[].identity_info.identity_id
              identity_type: $.rpc.output.gmv_max_data.shop_item_list[].identity_info.identity_type
              name: $.rpc.output.gmv_max_data.shop_item_list[].identity_info.name
              profile_image: $.rpc.output.gmv_max_data.shop_item_list[].identity_info.avatar_url
              store_id: $.rpc.output.gmv_max_data.shop_item_list[].identity_info.store_id
              user_name: $.rpc.output.gmv_max_data.shop_item_list[].identity_info.user_name
            item_id: $.rpc.output.gmv_max_data.shop_item_list[].item_id
            spu_id_list: $.rpc.output.gmv_max_data.shop_item_list[].spu_id_list
            text: $.rpc.output.gmv_max_data.shop_item_list[].title
            video_info[]:
            - bit_rate: $.rpc.output.gmv_max_data.shop_item_list[].video_info.bitrate
              definition: $.rpc.output.gmv_max_data.shop_item_list[].video_info.definition
              duration: $.rpc.output.gmv_max_data.shop_item_list[].video_info.duration
              format: $.rpc.output.gmv_max_data.shop_item_list[].video_info.format
              fps: $.rpc.output.gmv_max_data.shop_item_list[].video_info.fps
              height: $.rpc.output.gmv_max_data.shop_item_list[].video_info.height
              preview_url: $.rpc.output.gmv_max_data.shop_item_list[].video_info.play_url
              signature: $.rpc.output.gmv_max_data.shop_item_list[].video_info.file_md5
              size: $.rpc.output.gmv_max_data.shop_item_list[].video_info.file_size
              video_cover_url: $.rpc.output.gmv_max_data.shop_item_list[].video_info.cover_url
              video_id: $.rpc.output.gmv_max_data.shop_item_list[].video_info.video_id
              width: $.rpc.output.gmv_max_data.shop_item_list[].video_info.width
          location_ids: $.rpc.output.gmv_max_data.particle_locations
          operation_status: $.rpc.output.gmv_max_data.opt_status
          optimization_goal: $.rpc.output.gmv_max_data.optimize_goal
          placements: $.rpc.output.gmv_max_data.inventory_flow
          product_specific_type: $.rpc.output.gmv_max_data.product_specific_type
          product_video_specific_type: $.rpc.output.gmv_max_data.product_video_selection_type
          promotion_days:
            adjusted_roas_bid: $.rpc.output.gmv_max_data.promotion_days.adjusted_roas_bid
            auto_schedule_enabled: $.rpc.output.gmv_max_data.promotion_days.auto_schedule_enabled
            current_budget: $.rpc.output.gmv_max_data.promotion_days.current_budget
            custom_schedule_list[][]:
            - end_date: $.rpc.output.gmv_max_data.promotion_days.custom_schedule_list[].end_date
              start_date: $.rpc.output.gmv_max_data.promotion_days.custom_schedule_list[].start_date
            estimated_gross_revenue_increase: $.rpc.output.gmv_max_data.promotion_days.estimated_gross_revenue_increase
            is_enabled: $.rpc.output.gmv_max_data.promotion_days.is_enabled
            maximum_budget: $.rpc.output.gmv_max_data.promotion_days.maximum_budget
            next_increase: $.rpc.output.gmv_max_data.promotion_days.next_increase
            roas_bid_multiplier: $.rpc.output.gmv_max_data.promotion_days.roas_bid_multiplier
          roas_bid: $.rpc.output.gmv_max_data.roas_bid
          roi_protection_enabled: $.rpc.output.gmv_max_data.roi_protection_enabled
          schedule_end_time: $.rpc.output.gmv_max_data.end_time_stamp
          schedule_start_time: $.rpc.output.gmv_max_data.start_time_stamp
          schedule_type: $.rpc.output.gmv_max_data.schedule_type
          shopping_ads_type: $.rpc.output.gmv_max_data.promotion_flow_type
          store_authorized_bc_id: $.rpc.output.gmv_max_data.store_authorized_bc_id
          store_id: $.rpc.output.gmv_max_data.store_id
      x-open-scene-labels: []
      x-open-settings:
        pop_resp_nullvalue: true
servers:
- url: business-api.tiktok.com
