info:
  description: '{"en":"GmvMaxSessionUpdate","zh":"GmvMaxSessionUpdate"}'
  title: '{"en":"GmvMaxSessionUpdate","zh":"GmvMaxSessionUpdate"}'
  version: 1.0.0
openapi: 3.0.1
paths:
  /campaign/gmv_max/session/update/:
    post:
      operationId: Campaign Gmv_max Session Update
      parameters:
      - description: Authorized access token. For details, see [Authentication](https://ads.tiktok.com/marketing_api/docs?id=1738373164380162).
        in: query
        name: Access-Token
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                advertiser_id:
                  description: ''
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-convert:
                  - int64(%s)
                  x-open-field-id: 2
                  x-open-source: $.http.body.advertiser_id
                campaign_id:
                  description: ''
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-convert:
                  - int64(%s)
                  x-open-field-id: 1
                  x-open-source: $.http.body.campaign_id
                session:
                  description: ''
                  nullable: false
                  properties:
                    budget:
                      description: ''
                      format: double
                      nullable: false
                      type: number
                      x-open-allow-strlist: false
                      x-open-allow-strnum: false
                      x-open-field-id: 1
                      x-open-source: $.http.body.session.budget
                    schedule_end_time:
                      description: ''
                      nullable: false
                      type: string
                      x-open-allow-strlist: false
                      x-open-allow-strnum: false
                      x-open-convert:
                      - datetime_to_timestamp(%s,"date-time","utc")
                      x-open-field-id: 3
                      x-open-source: $.http.body.session.schedule_end_time
                    schedule_start_time:
                      description: ''
                      nullable: false
                      type: string
                      x-open-allow-strlist: false
                      x-open-allow-strnum: false
                      x-open-convert:
                      - datetime_to_timestamp(%s,"date-time","utc")
                      x-open-field-id: 2
                      x-open-source: $.http.body.session.schedule_start_time
                    schedule_type:
                      description: ''
                      nullable: false
                      type: string
                      x-open-allow-strlist: false
                      x-open-allow-strnum: false
                      x-open-enum:
                        enum_package_expired: false
                        enum_package_id: null
                        enum_package_name: null
                        enums:
                        - description: ''
                          is_valid: true
                          key: SCHEDULE_FROM_NOW
                          value: '1'
                        - description: ''
                          is_valid: true
                          key: SCHEDULE_START_END
                          value: '2'
                        key_format: string
                        strict: true
                        use_part: false
                        validate_only: false
                        value_format: int32
                      x-open-field-id: 4
                      x-open-source: $.http.body.session.schedule_type
                  type: object
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-field-id: 5
                  x-open-source: $.http.body.session
                session_id:
                  description: ''
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-convert:
                  - int64(%s)
                  x-open-field-id: 4
                  x-open-source: $.http.body.session_id
                store_id:
                  description: ''
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-convert:
                  - int64(%s)
                  x-open-field-id: 3
                  x-open-source: $.http.body.shop_id
              required:
              - campaign_id
              - advertiser_id
              - store_id
              - session_id
              - session
              type: object
              x-open-allow-strlist: false
              x-open-allow-strnum: false
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Response code. For the complete list of response
                      codes and descriptions, see [Appendix - Return Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                      Will be shown only if it is an error request.
                    format: int64
                    nullable: true
                    type: integer
                    x-open-allow-strlist: false
                    x-open-field-id: 4
                  data:
                    description: Returned data. The response for the SDK can be checked
                      in the document for the API given in the description.
                    nullable: true
                    properties: {}
                    type: object
                    x-open-allow-strlist: false
                    x-open-field-id: 1
                    x-open-source: $.rpc.output.data
                  message:
                    description: Response message. For details, see [Appendix - Return
                      Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 3
                  request_id:
                    description: The log ID of a request, which uniquely identifies
                      the request.
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 2
                type: object
                x-open-allow-strlist: false
          description: OK
      summary: Update GMV Max session [Smart Plus GMV Max Session Update](https://business-api.tiktok.com/portal/docs?id=1835247009119233)
      tags:
      - Campaign Creation
      x-open-allowlist: {}
      x-open-denylist: {}
      x-open-rules:
        base_rule: null
        extra_rule:
          base_source: []
          http_query_source: []
          http_source:
          - name: campaign_id
            required: true
            source: $.http.body.campaign_id
            type: number
          - name: advertiser_id
            required: true
            source: $.http.body.advertiser_id
            type: number
          - name: shop_id
            required: true
            source: $.http.body.store_id
            type: number
          - name: session_id
            required: true
            source: $.http.body.session_id
            type: number
          - children:
            - name: schedule_start_time
              required: false
              source: $.http.body.session.schedule_start_time
              type: number
            - name: schedule_end_time
              required: false
              source: $.http.body.session.schedule_end_time
              type: number
            - name: schedule_type
              required: false
              source: $.http.body.session.schedule_type
              type: number
            - is_expand: false
              name: budget
              required: false
              source: $.http.body.session.budget
              type: number
            is_expand: true
            name: session
            required: true
            type: object
        plugins:
          after_response: []
          before_request: []
        request_query_rule: null
        request_rule:
          advertiser_id: $.http.body.advertiser_id
          campaign_id: $.http.body.campaign_id
          session:
            budget: $.http.body.session.budget
            schedule_end_time: $.http.body.session.schedule_end_time
            schedule_start_time: $.http.body.session.schedule_start_time
            schedule_type: $.http.body.session.schedule_type
          session_id: $.http.body.session_id
          shop_id: $.http.body.store_id
        response_cookie: []
        response_header: []
        response_rule: null
      x-open-scene-labels: []
      x-open-settings:
        pop_resp_nullvalue: false
servers:
- url: business-api.tiktok.com
