info:
  description: "{\"en\":\"ShareableLinkCreate\",\"zh\":\"\u521B\u5EFAshareable link\"\
    }"
  title: "{\"en\":\"ShareableLinkCreate\",\"zh\":\"\u521B\u5EFAshareable link\"}"
  version: 1.0.0
openapi: 3.0.1
paths:
  /creative/shareable_link/create/:
    post:
      operationId: Creative Shareable_link Create
      parameters:
      - description: Authorized access token. For details, see [Authentication](https://ads.tiktok.com/marketing_api/docs?id=1738373164380162).
        in: query
        name: Access-Token
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                shared_assets:
                  description: ''
                  items:
                    nullable: false
                    properties:
                      asset_id:
                        description: ''
                        nullable: false
                        type: string
                        x-open-allow-strlist: false
                        x-open-allow-strnum: false
                        x-open-field-id: 1
                        x-open-source: $.http.body.shared_assets[].asset_id
                      asset_name:
                        description: ''
                        maxLength: 30
                        nullable: false
                        type: string
                        x-open-allow-strlist: false
                        x-open-allow-strnum: false
                        x-open-field-id: 2
                        x-open-source: $.http.body.shared_assets[].asset_name
                    type: object
                    x-open-allow-strlist: false
                    x-open-allow-strnum: false
                  maxItems: 20
                  nullable: false
                  type: array
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-field-id: 1
                  x-open-source: $.http.body.shared_assets
                sharer:
                  description: ''
                  maxLength: 30
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-field-id: 2
                  x-open-source: $.http.body.sharer
              required:
              - shared_assets
              - sharer
              type: object
              x-open-allow-strlist: false
              x-open-allow-strnum: false
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Response code. For the complete list of response
                      codes and descriptions, see [Appendix - Return Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                      Will be shown only if it is an error request.
                    format: int64
                    nullable: true
                    type: integer
                    x-open-allow-strlist: false
                    x-open-field-id: 4
                  data:
                    description: Returned data. The response for the SDK can be checked
                      in the document for the API given in the description.
                    nullable: true
                    properties: {}
                    type: object
                    x-open-allow-strlist: false
                    x-open-field-id: 1
                    x-open-source: $.rpc.output.data
                  message:
                    description: Response message. For details, see [Appendix - Return
                      Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 3
                  request_id:
                    description: The log ID of a request, which uniquely identifies
                      the request.
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 2
                type: object
                x-open-allow-strlist: false
          description: OK
      summary: ''
      tags:
      - Creative Management
      x-open-allowlist: {}
      x-open-denylist: {}
      x-open-rules:
        base_rule: null
        extra_rule:
          base_source: []
          http_query_source: []
          http_source:
          - children:
            - children:
              - name: asset_id
                required: false
                source: $.http.body.shared_assets[].asset_id
                type: string
              - name: asset_name
                required: false
                source: $.http.body.shared_assets[].asset_name
                type: string
              type: object
            name: shared_assets
            required: true
            source: $.http.body.shared_assets
            sub_type: object
            type: array
          - name: sharer
            required: true
            source: $.http.body.sharer
            type: string
        plugins:
          after_response: []
          before_request: []
        request_query_rule: null
        request_rule:
          shared_assets: $.http.body.shared_assets
          sharer: $.http.body.sharer
        response_cookie: []
        response_header: []
        response_rule:
          shareable_link: $.rpc.output.shareable_link
      x-open-scene-labels: []
      x-open-settings:
        pop_resp_nullvalue: false
servers:
- url: business-api.tiktok.com
