info:
  description: "{\"en\":\"Use this endpoint to get all audiences. The returned list\
    \ is paginated with a maximum paging size of 100. For each audience, information\
    \ like ID, name, type, creation time, expiration time will be returned in the\
    \ response. This endpoint returns both owned and shared audiences. You can use\
    \ is_creator to check whether this advertiser is the owner of this audience.\\\
    n\\nTo get more details about an audience, such as current status and modification\
    \ record, use [/dmp/custom_audience/get/](https://business-api.tiktok.com/portal/docs?id=1739940507792385)\
    \ instead.\",\"zh\":\"\u60A8\u53EF\u4EE5\u4F7F\u7528\u672C\u63A5\u53E3\u83B7\u53D6\
    \u4E00\u4E2A\u5E7F\u544A\u4E3B\u8D26\u53F7\u4E0B\u6240\u6709\u53D7\u4F17\u7684\
    \u4FE1\u606F\u3002\u8FD4\u56DE\u5217\u8868\u662F\u5206\u9875\u7684\uFF0C\u6700\
    \u5927\u5206\u9875\u5927\u5C0F\u4E3A100\u3002\u8BE5\u63A5\u53E3\u8FD4\u56DE\u7684\
    \u4FE1\u606F\u5305\u62EC\u6BCF\u4E2A\u53D7\u4F17\u7684ID\u3001\u540D\u79F0\u3001\
    \u7C7B\u578B\u3001\u521B\u5EFA\u65F6\u95F4\u3001\u8FC7\u671F\u65F6\u95F4\u7B49\
    \u3002\u8BE5\u63A5\u53E3\u4F1A\u8FD4\u56DE\u5C5E\u4E8E\u60A8\u7684\u53D7\u4F17\
    \u548C\u5171\u4EAB\u53D7\u4F17\u3002\u60A8\u53EF\u4EE5\u4F7F\u7528is_creator\u67E5\
    \u770B\u60A8\u662F\u5426\u4E3A\u8BE5\u53D7\u4F17\u7684\u62E5\u6709\u8005\u3002\
    \\n\\n\u5982\u679C\u9700\u8981\u83B7\u53D6\u53D7\u4F17\u8BE6\u7EC6\u4FE1\u606F\
    \uFF0C\u4F8B\u5982\u5F53\u524D\u72B6\u6001\u4EE5\u53CA\u5386\u53F2\u64CD\u4F5C\
    \u8BB0\u5F55\u8BE6\u60C5\uFF0C\u8BF7\u4F7F\u7528[/dmp/custom_audience/get/](https://business-api.tiktok.com/portal/docs?id=1739940507792385)\u63A5\
    \u53E3\u3002\"}"
  title: "{\"en\":\"Get all audiences\",\"zh\":\"\u83B7\u53D6\u53D7\u4F17\u5217\u8868\
    \"}"
  version: 1.0.0
openapi: 3.0.1
paths:
  /dmp/custom_audience/list/:
    get:
      operationId: Dmp Custom_audience List
      parameters:
      - description: Advertiser ID.
        in: query
        name: advertiser_id
        required: true
        schema:
          nullable: false
          type: string
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-convert:
          - int64(%s)
          x-open-source: $.http.query.advertiser_id
        x-open-field-id: 1
      - content:
          application/json:
            schema:
              items:
                nullable: false
                type: string
                x-open-allow-strlist: false
                x-open-allow-strnum: false
                x-open-convert:
                - int64(%s)
              maxItems: 100
              minItems: 1
              nullable: false
              type: array
              x-open-allow-strlist: false
              x-open-allow-strnum: false
              x-open-source: $.http.query.custom_audience_ids
        description: A list of Audience IDs. Length range is [1, 100].
        in: query
        name: custom_audience_ids
        required: false
        x-open-field-id: 2
      - description: "Current page number. Default value: 1. Value range: \u2265 1."
        in: query
        name: page
        required: false
        schema:
          default: 1
          format: int32
          minimum: 1
          nullable: false
          type: integer
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-convert:
          - int64(%s)
          x-open-source: $.http.query.page
        x-open-field-id: 3
      - description: 'Page size. Defaults is 10. Value range: 1-100.'
        in: query
        name: page_size
        required: false
        schema:
          default: 10
          format: int32
          maximum: 100
          minimum: 1
          nullable: false
          type: integer
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-convert:
          - int64(%s)
          x-open-source: $.http.query.page_size
        x-open-field-id: 4
      - description: Authorized access token. For details, see [Authentication](https://ads.tiktok.com/marketing_api/docs?id=1738373164380162).
        in: query
        name: Access-Token
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Response code. For the complete list of response
                      codes and descriptions, see [Appendix - Return Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                      Will be shown only if it is an error request.
                    format: int64
                    nullable: true
                    type: integer
                    x-open-allow-strlist: false
                    x-open-field-id: 4
                  data:
                    description: Returned data. The response for the SDK can be checked
                      in the document for the API given in the description.
                    nullable: true
                    properties: {}
                    type: object
                    x-open-allow-strlist: false
                    x-open-field-id: 1
                    x-open-source: $.rpc.output.data
                  message:
                    description: Response message. For details, see [Appendix - Return
                      Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 3
                  request_id:
                    description: The log ID of a request, which uniquely identifies
                      the request.
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 2
                type: object
                x-open-allow-strlist: false
          description: OK
      summary: Get all audiences [Dmp Custom_audience List](https://business-api.tiktok.com/portal/docs?id=1739940506015746)
      tags:
      - Audience
      x-open-allowlist: {}
      x-open-denylist: {}
      x-open-rules:
        base_rule: null
        extra_rule:
          base_source: []
          http_query_source: []
          http_source:
          - name: advertiser_id
            required: true
            source: $.http.query.advertiser_id
            type: number
          - children:
            - type: number
            is_expand: true
            name: custom_audience_ids
            required: false
            source: $.http.query.custom_audience_ids[]
            sub_type: number
            type: array
          - name: page
            required: false
            source: $.http.query.page
            type: number
          - name: page_size
            required: false
            source: $.http.query.page_size
            type: number
        plugins:
          after_response: []
          before_request: []
        request_query_rule: null
        request_rule:
          advertiser_id: $.http.query.advertiser_id
          custom_audience_ids: $.http.query.custom_audience_ids[]
          page: $.http.query.page
          page_size: $.http.query.page_size
        response_cookie: []
        response_header: []
        response_rule:
          list: $.rpc.output.data
          page_info: $.rpc.output.page_info
      x-open-scene-labels: []
      x-open-settings:
        pop_resp_nullvalue: false
servers:
- url: business-api.tiktok.com
