info:
  description: "{\"en\":\"Use this endpoint to update the details of an audience,\
    \ like audience name and audience file.\\n\\nThe TikTok API for Business supports\
    \ three types of audience modifications for customer file audience:\\n\\nREPLACE\
    \ (Replace)\uFF1AReplace previous (all) data files.\\nAPPEND (New): Add new data\
    \ files.\\nREMOVE (Remove): Remove specified data files.\",\"zh\":\"\u60A8\u53EF\
    \u4EE5\u4F7F\u7528\u672C\u63A5\u53E3\u4FEE\u6539\u5DF2\u521B\u5EFA\u7684\u53D7\
    \u4F17\u7FA4\u4F53\u3002\\n\\n\\n\u5BF9\u4E8E\u5BA2\u6237\u6587\u4EF6\u53D7\u4F17\
    \uFF0CTikTok API for Business\u652F\u6301\u4EE5\u4E0B\u4E09\u79CD\u4FEE\u6539\u64CD\
    \u4F5C\uFF1A\\n\\nREPLACE \uFF08\u66FF\u6362\uFF09\uFF1A\u7528\u53C2\u6570\u4E2D\
    \u7684\u6570\u636E\u6587\u4EF6\u53BB\u66FF\u6362\u4E4B\u524D\uFF08\u6240\u6709\
    \uFF09\u7684\u6570\u636E\u6587\u4EF6\\nAPPEND\uFF08\u65B0\u589E\uFF09 \uFF1A\u589E\
    \u52A0\u65B0\u7684\u6570\u636E\u6587\u4EF6\\nREMOVE \uFF08\u79FB\u9664\uFF09\uFF1A\
    \u79FB\u9664\u6307\u5B9A\u7684\u6570\u636E\u6587\u4EF6\\n\u63D0\u793A\"}"
  title: "{\"en\":\"Update an audience\",\"zh\":\"\u4FEE\u6539\u53D7\u4F17\"}"
  version: 1.0.0
openapi: 3.0.1
paths:
  /dmp/custom_audience/update/:
    post:
      operationId: Dmp Custom_audience Update
      parameters:
      - description: Authorized access token. For details, see [Authentication](https://ads.tiktok.com/marketing_api/docs?id=1738373164380162).
        in: query
        name: Access-Token
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                action:
                  default: REPLACE
                  description: 'Modification type. This field is valid when file_paths
                    is passed. Enum values: APPEND: Upload files to expand the Customer
                    File audience. Only data not included in the original file will
                    be added. REMOVE: Upload files to remove the Customer File audience.
                    Only the data that coincide with the original file will be removed.
                    REPLACE: Upload files to replace the Customer File audience. All
                    the data in the original file will be replaced. Default value:
                    REPLACE. Note: The APPEND, REMOVE and REPLACE operations will
                    fail if the audience size is less than 1,000 after the operation.'
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-enum:
                    enum_package_expired: false
                    enum_package_id: null
                    enum_package_name: null
                    enums:
                    - description: ''
                      is_valid: true
                      key: REPLACE
                      value: REPLACE
                    - description: ''
                      is_valid: true
                      key: APPEND
                      value: APPEND
                    - description: ''
                      is_valid: true
                      key: REMOVE
                      value: REMOVE
                    key_format: string
                    strict: true
                    use_part: false
                    validate_only: false
                    value_format: string
                  x-open-field-id: 6
                  x-open-source: $.http.body.action
                advertiser_id:
                  description: Advertiser ID.
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-convert:
                  - int64(%s)
                  x-open-field-id: 1
                  x-open-source: $.http.body.advertiser_id
                audience_enhancement:
                  description: ''
                  nullable: false
                  type: boolean
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-field-id: 7
                  x-open-source: $.http.body.audience_enhancement
                audience_sub_type:
                  description: 'Audience sub type, indicating the type of ads that
                    the audience can be used for. The allowed enum value: REACH_FREQUENCY(To
                    enable the audience to be used in Reach & Frequency campaigns).
                    It means you can only convert audience sub type from NORMAL to
                    REACH_FREQUENCY, but not the other way round. Note: If you update
                    this field, changes to other data fields will be ignored. If you
                    want to update a Lookalike audience, you cannot change the audience_sub_type
                    to REACH_FREQUENCY. Otherwise, an error will occur.'
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-field-id: 4
                  x-open-source: $.http.body.audience_sub_type
                context_info:
                  description: ''
                  nullable: false
                  properties:
                    core_user_id:
                      description: ''
                      format: int64
                      nullable: false
                      type: integer
                      x-open-allow-strlist: false
                      x-open-allow-strnum: false
                      x-open-field-id: 1
                      x-open-source: $.http.body.context_info.core_user_id
                  type: object
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-field-id: 8
                  x-open-source: $.http.body.context_info
                custom_audience_id:
                  description: Custom audience ID.
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-convert:
                  - int64(%s)
                  x-open-field-id: 2
                  x-open-source: $.http.body.custom_audience_id
                custom_audience_name:
                  description: 'New name for the audience. Length limit: 128 characters.
                    You must pass in either this field or file_paths.'
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-field-id: 3
                  x-open-source: $.http.body.custom_audience_name
                file_paths:
                  description: The files you upload to update the Customer File audience.
                    You must pass in either this field or custom_audience_name. The
                    recommended size is <50 per request to ensure stability. Once
                    you pass in this field, you can specify the modification type
                    (APPEND, REMOVE or REPLACE) via action. The files must be encrypted
                    with the same encryption method/type with the audience that you
                    want to update.
                  items:
                    nullable: false
                    type: string
                    x-open-allow-strlist: false
                    x-open-allow-strnum: false
                  nullable: false
                  type: array
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-field-id: 5
                  x-open-source: $.http.body.file_paths
              required:
              - advertiser_id
              - custom_audience_id
              type: object
              x-open-allow-strlist: false
              x-open-allow-strnum: false
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Response code. For the complete list of response
                      codes and descriptions, see [Appendix - Return Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                      Will be shown only if it is an error request.
                    format: int64
                    nullable: true
                    type: integer
                    x-open-allow-strlist: false
                    x-open-field-id: 4
                  data:
                    description: Returned data. The response for the SDK can be checked
                      in the document for the API given in the description.
                    nullable: true
                    properties: {}
                    type: object
                    x-open-allow-strlist: false
                    x-open-field-id: 1
                    x-open-source: $.rpc.output.data
                  message:
                    description: Response message. For details, see [Appendix - Return
                      Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 3
                  request_id:
                    description: The log ID of a request, which uniquely identifies
                      the request.
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 2
                type: object
                x-open-allow-strlist: false
          description: OK
      summary: Update the details of an audience [Dmp Custom_audience Update](https://business-api.tiktok.com/portal/docs?id=1739940572667906)
      tags:
      - Audience
      x-open-allowlist: {}
      x-open-denylist: {}
      x-open-rules:
        base_rule: null
        extra_rule:
          base_source: []
          http_query_source: []
          http_source:
          - name: advertiser_id
            required: true
            source: $.http.body.advertiser_id
            type: number
          - name: custom_audience_id
            required: true
            source: $.http.body.custom_audience_id
            type: number
          - name: custom_audience_name
            required: false
            source: $.http.body.custom_audience_name
            type: string
          - name: audience_sub_type
            required: false
            source: $.http.body.audience_sub_type
            type: string
          - children:
            - type: string
            is_expand: true
            name: file_paths
            required: false
            source: $.http.body.file_paths
            sub_type: string
            type: array
          - name: action
            required: false
            source: $.http.body.action
            type: string
          - name: audience_enhancement
            required: false
            source: $.http.body.audience_enhancement
            type: boolean
          - children:
            - name: core_user_id
              required: false
              source: $.context.core_user_id
              type: number
            is_expand: true
            name: context_info
            required: false
            source: ''
            type: object
        plugins:
          after_response: []
          before_request: []
        request_query_rule: null
        request_rule:
          action: $.http.body.action
          advertiser_id: $.http.body.advertiser_id
          audience_enhancement: $.http.body.audience_enhancement
          audience_sub_type: $.http.body.audience_sub_type
          context_info:
            core_user_id: $.context.core_user_id
          custom_audience_id: $.http.body.custom_audience_id
          custom_audience_name: $.http.body.custom_audience_name
          file_paths: $.http.body.file_paths
        response_cookie: []
        response_header: []
        response_rule: null
      x-open-scene-labels: []
      x-open-settings:
        pop_resp_nullvalue: false
servers:
- url: biz-api.tiktok.com
