info:
  description: '{"en":"GmvMaxExclusiveAuthorizationCreate","zh":"GmvMaxExclusiveAuthorizationCreate"}'
  title: '{"en":"GmvMaxExclusiveAuthorizationCreate","zh":"GmvMaxExclusiveAuthorizationCreate"}'
  version: 1.0.0
openapi: 3.0.1
paths:
  /gmv_max/exclusive_authorization/create/:
    post:
      operationId: Gmv_max Exclusive_authorization Create
      parameters:
      - description: Authorized access token. For details, see [Authentication](https://ads.tiktok.com/marketing_api/docs?id=1738373164380162).
        in: query
        name: Access-Token
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                advertiser_id:
                  description: ''
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-convert:
                  - int64(%s)
                  x-open-field-id: 1
                  x-open-source: $.http.body.advertiser_id
                store_authorized_bc_id:
                  description: ''
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-convert:
                  - int64(%s)
                  x-open-field-id: 3
                  x-open-source: $.http.body.bc_id
                store_id:
                  description: ''
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-convert:
                  - int64(%s)
                  x-open-field-id: 2
                  x-open-source: $.http.body.store_id
              required:
              - advertiser_id
              - store_id
              - store_authorized_bc_id
              type: object
              x-open-allow-strlist: false
              x-open-allow-strnum: false
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Response code. For the complete list of response
                      codes and descriptions, see [Appendix - Return Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                      Will be shown only if it is an error request.
                    format: int64
                    nullable: true
                    type: integer
                    x-open-allow-strlist: false
                    x-open-field-id: 4
                  data:
                    description: Returned data. The response for the SDK can be checked
                      in the document for the API given in the description.
                    nullable: true
                    properties: {}
                    type: object
                    x-open-allow-strlist: false
                    x-open-field-id: 1
                    x-open-source: $.rpc.output.data
                  message:
                    description: Response message. For details, see [Appendix - Return
                      Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 3
                  request_id:
                    description: The log ID of a request, which uniquely identifies
                      the request.
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 2
                type: object
                x-open-allow-strlist: false
          description: OK
      summary: Create GMV Max exclusive authorization [Smart Plus GMV Max Exclusive
        Authorization Create](https://business-api.tiktok.com/portal/docs?id=1822001200356354)
      tags:
      - Store
      x-open-allowlist: {}
      x-open-denylist: {}
      x-open-rules:
        base_rule: null
        extra_rule:
          base_source: []
          http_query_source: []
          http_source:
          - name: advertiser_id
            required: true
            source: $.http.body.advertiser_id
            type: number
          - name: store_id
            required: true
            source: $.http.body.store_id
            type: number
          - name: mutex_asset_id
            required: false
            source: $.http.body.mutex_asset_id
            type: string
          - name: bc_id
            required: true
            source: $.http.body.store_authorized_bc_id
            type: number
        plugins:
          after_response: []
          before_request: []
        request_query_rule: null
        request_rule:
          advertiser_id: $.http.body.advertiser_id
          bc_id: $.http.body.store_authorized_bc_id
          mutex_asset_id: $.http.body.mutex_asset_id
          store_id: $.http.body.store_id
        response_cookie: []
        response_header: []
        response_rule: null
      x-open-scene-labels: []
      x-open-settings:
        pop_resp_nullvalue: false
servers:
- url: business-api.tiktok.com
