info:
  description: "{\"en\":\"Use this endpoint to get rules based on the values of certain\
    \ filters.\",\"zh\":\"\u60A8\u53EF\u4EE5\u4F7F\u7528\u672C\u63A5\u53E3\u6839\u636E\
    \u6761\u4EF6\u83B7\u53D6\u89C4\u5219\u3002\"}"
  title: "{\"en\":\"Get rules by filters\",\"zh\":\"\u6839\u636E\u6761\u4EF6\u83B7\
    \u53D6\u89C4\u5219\"}"
  version: 1.0.0
openapi: 3.0.1
paths:
  /optimizer/rule/list/:
    get:
      operationId: Optimizer Rule List
      parameters:
      - description: ''
        in: query
        name: advertiser_id
        required: true
        schema:
          type: string
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-convert:
          - int64(%s)
          x-open-source: $.http.query.advertiser_id
        x-open-field-id: 1
      - description: ''
        in: query
        name: filtering
        required: false
        schema:
          $ref: ./openapi.yaml#/definitions/FilteringOptimizerRuleList
        x-open-field-id: 2
      - description: ''
        in: query
        name: tzone
        required: false
        schema:
          default: UTC
          nullable: false
          type: string
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-source: $.http.query.tzone
        x-open-field-id: 3
      - description: ''
        in: query
        name: page
        required: false
        schema:
          default: 1
          format: int64
          nullable: false
          type: integer
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-source: $.http.query.page
        x-open-field-id: 4
      - description: ''
        in: query
        name: page_size
        required: false
        schema:
          default: 10
          format: int64
          nullable: false
          type: integer
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-source: $.http.query.page_size
        x-open-field-id: 5
      - description: Authorized access token. For details, see [Authentication](https://ads.tiktok.com/marketing_api/docs?id=1738373164380162).
        in: query
        name: Access-Token
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Response code. For the complete list of response
                      codes and descriptions, see [Appendix - Return Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                      Will be shown only if it is an error request.
                    format: int64
                    nullable: true
                    type: integer
                    x-open-allow-strlist: false
                    x-open-field-id: 4
                  data:
                    description: Returned data. The response for the SDK can be checked
                      in the document for the API given in the description.
                    nullable: true
                    properties: {}
                    type: object
                    x-open-allow-strlist: false
                    x-open-field-id: 1
                    x-open-source: $.rpc.output.data
                  message:
                    description: Response message. For details, see [Appendix - Return
                      Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 3
                  request_id:
                    description: The log ID of a request, which uniquely identifies
                      the request.
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 2
                type: object
                x-open-allow-strlist: false
          description: OK
      summary: Get rules based on the values of certain filters. [Optimizer Rule List](https://business-api.tiktok.com/portal/docs?id=1738768861976578)
      tags:
      - Automated_Rules
      x-open-allowlist: {}
      x-open-denylist: {}
      x-open-rules:
        base_rule: null
        extra_rule:
          base_source: []
          http_query_source: []
          http_source:
          - name: advertiser_id
            required: true
            source: $.http.query.advertiser_id
            type: number
          - children:
            - name: status
              required: false
              type: string
            - children:
              - type: string
              is_expand: true
              name: rule_info
              required: false
              sub_type: string
              type: array
            - name: data_dimension
              required: false
              type: string
            - name: action
              required: false
              type: string
            - children:
              - type: string
              is_expand: true
              name: time
              required: false
              sub_type: string
              type: array
            is_expand: true
            name: filtering
            required: false
            source: $.http.query.filtering
            type: object
          - name: tzone
            required: false
            source: $.http.query.tzone
            type: string
          - name: page
            required: false
            source: $.http.query.page
            type: number
          - name: page_size
            required: false
            source: $.http.query.page_size
            type: number
        plugins:
          after_response: []
          before_request: []
        request_query_rule: null
        request_rule:
          advertiser_id: $.http.query.advertiser_id
          filtering: $.http.query.filtering
          page: $.http.query.page
          page_size: $.http.query.page_size
          tzone: $.http.query.tzone
        response_cookie: []
        response_header: []
        response_rule:
          page_info: $.rpc.output.page_info
          rules: $.rpc.output.rules
      x-open-scene-labels: []
      x-open-settings:
        pop_resp_nullvalue: false
servers:
- url: business-api.tiktok.com
