info:
  description: '{"en":"Pixel List","zh":"Pixel List"}'
  title: '{"en":"Pixel List","zh":"Pixel List"}'
  version: 1.0.0
openapi: 3.0.1
paths:
  /pixel/list/:
    get:
      operationId: Pixel List
      parameters:
      - description: ''
        in: query
        name: advertiser_id
        required: true
        schema:
          nullable: false
          type: string
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-convert:
          - int64(%s)
          x-open-source: $.http.query.advertiser_id
        x-open-field-id: 1
      - description: ''
        in: query
        name: pixel_id
        required: false
        schema:
          nullable: false
          type: string
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-convert:
          - int64(%s)
          x-open-source: $.http.query.pixel_id
        x-open-field-id: 2
      - description: ''
        in: query
        name: code
        required: false
        schema:
          nullable: false
          type: string
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-source: $.http.query.code
        x-open-field-id: 3
      - description: ''
        in: query
        name: name
        required: false
        schema:
          nullable: false
          type: string
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-source: $.http.query.name
        x-open-field-id: 4
      - description: ''
        in: query
        name: order_by
        required: false
        schema:
          default: EARLIEST_CREATE
          nullable: false
          type: string
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-enum:
            enum_package_expired: false
            enum_package_id: null
            enum_package_name: null
            enums:
            - description: ''
              is_valid: true
              key: LATEST_CREATE
              value: '0'
            - description: ''
              is_valid: true
              key: EARLIEST_CREATE
              value: '1'
            key_format: string
            strict: true
            use_part: false
            validate_only: false
            value_format: int32
          x-open-source: $.http.query.order_by
        x-open-field-id: 5
      - content:
          application/json:
            schema:
              nullable: false
              properties:
                available_for_catalog_only:
                  default: false
                  description: ''
                  nullable: false
                  type: boolean
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-field-id: 1
                  x-open-source: $.http.query.filtering.available_for_catalog_only
              type: object
              x-open-allow-strlist: false
              x-open-allow-strnum: false
              x-open-source: $.http.query.filtering
        description: ''
        in: query
        name: filtering
        required: false
        x-open-field-id: 6
      - description: ''
        in: query
        name: page
        required: false
        schema:
          format: int64
          minimum: 1
          nullable: false
          type: integer
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-source: $.http.query.page
        x-open-field-id: 7
      - description: ''
        in: query
        name: page_size
        required: false
        schema:
          format: int64
          maximum: 20
          minimum: 1
          nullable: false
          type: integer
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-source: $.http.query.page_size
        x-open-field-id: 8
      - description: Authorized access token. For details, see [Authentication](https://ads.tiktok.com/marketing_api/docs?id=1738373164380162).
        in: query
        name: Access-Token
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Response code. For the complete list of response
                      codes and descriptions, see [Appendix - Return Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                      Will be shown only if it is an error request.
                    format: int64
                    nullable: true
                    type: integer
                    x-open-allow-strlist: false
                    x-open-field-id: 4
                  data:
                    description: Returned data. The response for the SDK can be checked
                      in the document for the API given in the description.
                    nullable: true
                    properties: {}
                    type: object
                    x-open-allow-strlist: false
                    x-open-field-id: 1
                    x-open-source: $.rpc.output.data
                  message:
                    description: Response message. For details, see [Appendix - Return
                      Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 3
                  request_id:
                    description: The log ID of a request, which uniquely identifies
                      the request.
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 2
                type: object
                x-open-allow-strlist: false
          description: OK
      summary: Obtain a list of Pixel information. [Pixel List](https://business-api.tiktok.com/portal/docs?id=1740858697598978)
      tags:
      - Measurement
      x-open-allowlist: {}
      x-open-denylist: {}
      x-open-rules:
        base_rule: null
        extra_rule:
          base_source: []
          http_query_source: []
          http_source:
          - name: advertiser_id
            required: true
            source: $.http.query.advertiser_id
            type: number
          - name: pixel_id
            required: false
            source: $.http.query.pixel_id
            type: number
          - name: code
            required: false
            source: $.http.query.code
            type: string
          - name: name
            required: false
            source: $.http.query.name
            type: string
          - name: order_by
            required: false
            source: $.http.query.order_by
            type: number
          - children:
            - name: available_for_catalog_only
              required: false
              source: $.http.query.filtering.available_for_catalog_only
              type: boolean
            name: filtering
            required: false
            source: $.http.query.filtering
            type: object
          - name: page
            required: false
            source: $.http.query.page
            type: number
          - name: page_size
            required: false
            source: $.http.query.page_size
            type: number
        plugins:
          after_response: []
          before_request: []
        request_query_rule: null
        request_rule:
          advertiser_id: $.http.query.advertiser_id
          code: $.http.query.code
          filtering: $.http.query.filtering
          name: $.http.query.name
          order_by: $.http.query.order_by
          page: $.http.query.page
          page_size: $.http.query.page_size
          pixel_id: $.http.query.pixel_id
        response_cookie: []
        response_header: []
        response_rule:
          page_info: $.rpc.output.page_info
          pixels: $.rpc.output.pixels
      x-open-scene-labels: []
      x-open-settings:
        pop_resp_nullvalue: false
servers:
- url: business-api.tiktok.com
