info:
  description: '{"en":"SPCampaignUpdate","zh":"SPCampaignUpdate"}'
  title: '{"en":"SPCampaignUpdate","zh":"SPCampaignUpdate"}'
  version: 1.0.0
openapi: 3.0.1
paths:
  /smart_plus/campaign/update/:
    post:
      operationId: Smart_plus Campaign Update
      parameters:
      - description: Authorized access token. For details, see [Authentication](https://ads.tiktok.com/marketing_api/docs?id=1738373164380162).
        in: query
        name: Access-Token
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                advertiser_id:
                  description: ''
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-convert:
                  - int64(%s)
                  x-open-field-id: 1
                  x-open-source: $.http.body.advertiser_id
                budget:
                  description: ''
                  format: double
                  nullable: false
                  type: number
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-field-id: 4
                  x-open-source: $.http.body.budget
                campaign_id:
                  description: ''
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-convert:
                  - int64(%s)
                  x-open-field-id: 2
                  x-open-source: $.http.body.campaign_id
                campaign_name:
                  description: ''
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-field-id: 3
                  x-open-source: $.http.body.name
                po_number:
                  description: ''
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-field-id: 5
              required:
              - advertiser_id
              - campaign_id
              type: object
              x-open-allow-strlist: false
              x-open-allow-strnum: false
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Response code. For the complete list of response
                      codes and descriptions, see [Appendix - Return Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                      Will be shown only if it is an error request.
                    format: int64
                    nullable: true
                    type: integer
                    x-open-allow-strlist: false
                    x-open-field-id: 4
                  data:
                    description: Returned data. The response for the SDK can be checked
                      in the document for the API given in the description.
                    nullable: true
                    properties: {}
                    type: object
                    x-open-allow-strlist: false
                    x-open-field-id: 1
                    x-open-source: $.rpc.output.data
                  message:
                    description: Response message. For details, see [Appendix - Return
                      Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 3
                  request_id:
                    description: The log ID of a request, which uniquely identifies
                      the request.
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 2
                type: object
                x-open-allow-strlist: false
          description: OK
      summary: Update an existing campaign [Smart Plus Campaign Update]
      tags:
      - Campaign Creation
      x-open-allowlist: {}
      x-open-denylist: {}
      x-open-rules:
        base_rule: null
        extra_rule:
          base_source: []
          http_query_source: []
          http_source:
          - name: advertiser_id
            required: true
            source: $.http.body.advertiser_id
            type: number
          - name: campaign_id
            required: true
            source: $.http.body.campaign_id
            type: number
          - name: name
            required: false
            source: $.http.body.campaign_name
            type: string
          - name: budget
            required: false
            source: $.http.body.budget
            type: number
          - name: po_number
            required: false
            source: $.http.body.po_number
            type: string
        plugins:
          after_response: []
          before_request: []
        request_query_rule: null
        request_rule:
          advertiser_id: $.http.body.advertiser_id
          budget: $.http.body.budget
          campaign_id: $.http.body.campaign_id
          name: $.http.body.campaign_name
          po_number: $.http.body.po_number
        response_cookie: []
        response_header: []
        response_rule:
          advertiser_id: $.rpc.output.campaign_data.advertiser_id
          app_id: $.rpc.output.campaign_data.app_id
          app_promotion_type: $.rpc.output.campaign_data.app_campaign_type
          budget: $.rpc.output.campaign_data.budget
          budget_mode: $.rpc.output.campaign_data.budget_mode
          budget_optimize_on: $.rpc.output.campaign_data.budget_optimize_on
          campaign_app_profile_page_state: $.rpc.output.campaign_data.campaign_app_profile_page_type
          campaign_id: $.rpc.output.campaign_data.campaign_id
          campaign_name: $.rpc.output.campaign_data.name
          campaign_type: $.rpc.output.campaign_data.dedicate_type
          catalog_enabled: $.rpc.output.campaign_data.catalog_enabled
          catalog_type: $.rpc.output.campaign_data.catalog_type
          create_time: $.rpc.output.campaign_data.create_time
          disable_skan_campaign: $.rpc.output.campaign_data.disable_skan_campaign
          is_advanced_dedicated_campaign: $.rpc.output.campaign_data.is_advanced_dedicated_campaign
          is_promotional_campaign: $.rpc.output.campaign_data.is_promotional_campaign
          modify_time: $.rpc.output.campaign_data.modify_time
          objective_type: $.rpc.output.campaign_data.objective_type
          operation_status: $.rpc.output.campaign_data.operation_status
          po_number: $.rpc.output.campaign_data.po_number
          postback_window_mode: $.rpc.output.campaign_data.dc_postback_mode
          sales_destination: $.rpc.output.campaign_data.sales_destination
          secondary_status: $.rpc.output.campaign_data.secondary_status
          smart_plus_adgroup_mode: $.rpc.output.campaign_data.spc_multi_ad_mode
          special_industries: $.rpc.output.campaign_data.industry_types
      x-open-scene-labels: []
      x-open-settings:
        pop_resp_nullvalue: true
servers:
- url: business-api.tiktok.com
