info:
  description: "{\"en\":\"Use this endpoint to get additional interest categories\
    \ by ID.\\n\\n\",\"zh\":\"\u60A8\u53EF\u4EE5\u4F7F\u7528\u672C\u63A5\u53E3\u901A\
    \u8FC7 ID \u83B7\u53D6\u76F8\u5E94\u7684\u5176\u4ED6\u5174\u8DA3\u5206\u7C7B\u3002\
    \"}"
  title: "{\"en\":\"Get additional interest categories by ID\",\"zh\":\"\u901A\u8FC7\
    \ ID \u83B7\u53D6\u5176\u4ED6\u5174\u8DA3\u5206\u7C7B\"}"
  version: 1.0.0
openapi: 3.0.1
paths:
  /tool/interest_keyword/get/:
    get:
      operationId: Tool Interest_keyword Get
      parameters:
      - description: Advertiser ID.
        in: query
        name: advertiser_id
        required: true
        schema:
          nullable: false
          type: string
          x-open-allow-strlist: false
          x-open-allow-strnum: false
          x-open-convert:
          - int64(%s)
          x-open-source: $.http.query.advertiser_id
        x-open-field-id: 1
      - content:
          application/json:
            schema:
              nullable: false
              properties:
                audience_type:
                  default: GENERAL_INTEREST
                  description: 'The audience type that you want to filter by. Enum
                    values: GENERAL_INTEREST: General interest. The audiences have
                    a general, long-term interest in a video category. PURCHASE_INTENTION:
                    Purchase intent. The audiences'' recent behavior suggests they
                    may buy something related to a content category. Default value:
                    GENERAL_INTEREST.'
                  nullable: false
                  type: string
                  x-open-allow-strlist: false
                  x-open-allow-strnum: false
                  x-open-enum:
                    enum_package_expired: false
                    enum_package_id: 1802435246858242
                    enum_package_name: KeywordScene
                    enums:
                    - description: ''
                      is_valid: true
                      key: GENERAL_INTEREST
                      value: '12'
                    - description: ''
                      is_valid: false
                      key: HASHTAG_TARGETING
                      value: '13'
                    - description: ''
                      is_valid: true
                      key: PURCHASE_INTENTION
                      value: '14'
                    key_format: string
                    strict: true
                    use_part: true
                    validate_only: false
                    value_format: int32
                  x-open-field-id: 1
                  x-open-source: $.http.query.filtering.audience_type
              type: object
              x-open-allow-strlist: false
              x-open-allow-strnum: false
              x-open-source: $.http.query.filtering
        description: Filtering conditions.
        in: query
        name: filtering
        required: false
        x-open-field-id: 2
      - content:
          application/json:
            schema:
              items:
                nullable: false
                properties:
                  keyword_id:
                    description: Additional interest category ID.
                    nullable: false
                    type: string
                    x-open-allow-strlist: false
                    x-open-allow-strnum: false
                    x-open-convert:
                    - int64(%s)
                    x-open-field-id: 1
                    x-open-source: $.http.query.keyword_query[].keyword_id
                  language:
                    default: en
                    description: 'Additional interest category language. Default value:
                      en. Supported languages: fr, id, it, ja, ms, ar, vi, en, ru,
                      es, th, tr, hi, zh, de, ko.'
                    nullable: false
                    type: string
                    x-open-allow-strlist: false
                    x-open-allow-strnum: false
                    x-open-enum:
                      enum_package_expired: false
                      enum_package_id: 1802434494012417
                      enum_package_name: Language
                      enums:
                      - description: ''
                        is_valid: true
                        key: ar
                        value: '15'
                      - description: ''
                        is_valid: true
                        key: de
                        value: '3'
                      - description: ''
                        is_valid: true
                        key: en
                        value: '1'
                      - description: ''
                        is_valid: true
                        key: es
                        value: '4'
                      - description: ''
                        is_valid: true
                        key: fr
                        value: '5'
                      - description: ''
                        is_valid: true
                        key: hi
                        value: '6'
                      - description: ''
                        is_valid: true
                        key: id
                        value: '7'
                      - description: ''
                        is_valid: true
                        key: it
                        value: '8'
                      - description: ''
                        is_valid: true
                        key: ja
                        value: '2'
                      - description: ''
                        is_valid: true
                        key: ko
                        value: '9'
                      - description: ''
                        is_valid: true
                        key: ms
                        value: '10'
                      - description: ''
                        is_valid: true
                        key: ru
                        value: '11'
                      - description: ''
                        is_valid: true
                        key: th
                        value: '12'
                      - description: ''
                        is_valid: true
                        key: tr
                        value: '13'
                      - description: ''
                        is_valid: true
                        key: vi
                        value: '14'
                      - description: ''
                        is_valid: true
                        key: zh
                        value: '0'
                      key_format: string
                      strict: true
                      use_part: false
                      validate_only: false
                      value_format: int32
                    x-open-field-id: 2
                    x-open-source: $.http.query.keyword_query[].language
                required:
                - keyword_id
                type: object
                x-open-allow-strlist: false
                x-open-allow-strnum: false
              maxItems: 50
              minItems: 1
              nullable: false
              type: array
              x-open-allow-strlist: false
              x-open-allow-strnum: false
              x-open-source: $.http.query.keyword_query
        description: Information of the additional interest category you want to get.
          Max size = 50.
        in: query
        name: keyword_query
        required: false
        x-open-field-id: 3
      - description: Authorized access token. For details, see [Authentication](https://ads.tiktok.com/marketing_api/docs?id=1738373164380162).
        in: query
        name: Access-Token
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  code:
                    description: Response code. For the complete list of response
                      codes and descriptions, see [Appendix - Return Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                      Will be shown only if it is an error request.
                    format: int64
                    nullable: true
                    type: integer
                    x-open-allow-strlist: false
                    x-open-field-id: 4
                  data:
                    description: Returned data. The response for the SDK can be checked
                      in the document for the API given in the description.
                    nullable: true
                    properties: {}
                    type: object
                    x-open-allow-strlist: false
                    x-open-field-id: 1
                    x-open-source: $.rpc.output.data
                  message:
                    description: Response message. For details, see [Appendix - Return
                      Codes](https://ads.tiktok.com/marketing_api/docs?id=1737172488964097).
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 3
                  request_id:
                    description: The log ID of a request, which uniquely identifies
                      the request.
                    nullable: true
                    type: string
                    x-open-allow-strlist: false
                    x-open-field-id: 2
                type: object
                x-open-allow-strlist: false
          description: OK
      summary: Get additional interest categories by ID [Tool Interest_keyword Get](https://ads.tiktok.com/marketing_api/docs?id=1763590894544897)
      tags:
      - Tool
      x-open-allowlist: {}
      x-open-denylist: {}
      x-open-rules:
        base_rule: null
        extra_rule:
          base_source: []
          http_query_source: []
          http_source:
          - name: advertiser_id
            required: true
            source: $.http.query.advertiser_id
            type: number
          - children:
            - name: audience_type
              required: false
              source: $.http.query.filtering.audience_type
              type: number
            is_expand: true
            name: filtering
            required: false
            type: object
          - children:
            - children:
              - name: keyword_id
                required: true
                source: $.http.query.keyword_query[].keyword_id
                type: number
              - name: language
                required: false
                source: $.http.query.keyword_query[].language
                type: number
              is_expand: true
              type: object
            is_expand: true
            name: keyword_query
            required: false
            sub_type: object
            type: array
        plugins:
          after_response: []
          before_request: []
        request_query_rule: null
        request_rule:
          advertiser_id: $.http.query.advertiser_id
          filtering:
            audience_type: $.http.query.filtering.audience_type
          keyword_query[][]:
          - keyword_id: $.http.query.keyword_query[].keyword_id
            language: $.http.query.keyword_query[].language
        response_cookie: []
        response_header: []
        response_rule:
          keywords[][]:
          - keyword: $.rpc.output.keywords[].keyword
            keyword_id: $.rpc.output.keywords[].keyword_id
            status: $.rpc.output.keywords[].status
      x-open-scene-labels: []
      x-open-settings:
        pop_resp_nullvalue: false
servers:
- url: business-api.tiktok.com
