# coding: utf-8

"""
 Copyright 2023 TikTok Pte. Ltd.

 This source code is licensed under the MIT license found in
 the LICENSE file in the root directory of this source tree.
"""
import pprint
import re  # noqa: F401

import six

class AdAcoBodyCardList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'card_id': 'str'
    }

    attribute_map = {
        'card_id': 'card_id'
    }

    def __init__(self, card_id=None):  # noqa: E501
        """AdAcoBodyCardList - a model defined in Swagger"""  # noqa: E501
        self._card_id = None
        self.discriminator = None
        if card_id is not None:
            self.card_id = card_id

    @property
    def card_id(self):
        """Gets the card_id of this AdAcoBodyCardList.  # noqa: E501

        Display Card ID, gift code card ID, premium badge ID, Countdown Sticker ID, or Download Card ID.<ul><li> To learn about how to get a display card ID or download card ID, please see [Use Cards in Ads](https://ads.tiktok.com/marketing_api/docs?id=1738963975941122).To learn about how to get a premium badge ID, see [Premium Add-ons](https://ads.tiktok.com/marketing_api/docs?id=1749019676181505). Premium badges are only supported in R&F ads.To learn about how to get a Countdown Sticker ID, see [Stickers](https://ads.tiktok.com/marketing_api/docs?id=1749019667506177).  # noqa: E501

        :return: The card_id of this AdAcoBodyCardList.  # noqa: E501
        :rtype: str
        """
        return self._card_id

    @card_id.setter
    def card_id(self, card_id):
        """Sets the card_id of this AdAcoBodyCardList.

        Display Card ID, gift code card ID, premium badge ID, Countdown Sticker ID, or Download Card ID.<ul><li> To learn about how to get a display card ID or download card ID, please see [Use Cards in Ads](https://ads.tiktok.com/marketing_api/docs?id=1738963975941122).To learn about how to get a premium badge ID, see [Premium Add-ons](https://ads.tiktok.com/marketing_api/docs?id=1749019676181505). Premium badges are only supported in R&F ads.To learn about how to get a Countdown Sticker ID, see [Stickers](https://ads.tiktok.com/marketing_api/docs?id=1749019667506177).  # noqa: E501

        :param card_id: The card_id of this AdAcoBodyCardList.  # noqa: E501
        :type: str
        """

        self._card_id = card_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdAcoBodyCardList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdAcoBodyCardList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
