# coding: utf-8

"""
 Copyright 2023 TikTok Pte. Ltd.

 This source code is licensed under the MIT license found in
 the LICENSE file in the root directory of this source tree.
"""
import pprint
import re  # noqa: F401

import six

class AssetUnassignBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asset_id': 'str',
        'asset_type': 'str',
        'bc_id': 'str',
        'user_id': 'str'
    }

    attribute_map = {
        'asset_id': 'asset_id',
        'asset_type': 'asset_type',
        'bc_id': 'bc_id',
        'user_id': 'user_id'
    }

    def __init__(self, asset_id=None, asset_type=None, bc_id=None, user_id=None):  # noqa: E501
        """AssetUnassignBody - a model defined in Swagger"""  # noqa: E501
        self._asset_id = None
        self._asset_type = None
        self._bc_id = None
        self._user_id = None
        self.discriminator = None
        self.asset_id = asset_id
        self.asset_type = asset_type
        self.bc_id = bc_id
        self.user_id = user_id

    @property
    def asset_id(self):
        """Gets the asset_id of this AssetUnassignBody.  # noqa: E501


        :return: The asset_id of this AssetUnassignBody.  # noqa: E501
        :rtype: str
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this AssetUnassignBody.


        :param asset_id: The asset_id of this AssetUnassignBody.  # noqa: E501
        :type: str
        """
        if asset_id is None:
            raise ValueError("Invalid value for `asset_id`, must not be `None`")  # noqa: E501

        self._asset_id = asset_id

    @property
    def asset_type(self):
        """Gets the asset_type of this AssetUnassignBody.  # noqa: E501


        :return: The asset_type of this AssetUnassignBody.  # noqa: E501
        :rtype: str
        """
        return self._asset_type

    @asset_type.setter
    def asset_type(self, asset_type):
        """Sets the asset_type of this AssetUnassignBody.


        :param asset_type: The asset_type of this AssetUnassignBody.  # noqa: E501
        :type: str
        """
        if asset_type is None:
            raise ValueError("Invalid value for `asset_type`, must not be `None`")  # noqa: E501

        self._asset_type = asset_type

    @property
    def bc_id(self):
        """Gets the bc_id of this AssetUnassignBody.  # noqa: E501


        :return: The bc_id of this AssetUnassignBody.  # noqa: E501
        :rtype: str
        """
        return self._bc_id

    @bc_id.setter
    def bc_id(self, bc_id):
        """Sets the bc_id of this AssetUnassignBody.


        :param bc_id: The bc_id of this AssetUnassignBody.  # noqa: E501
        :type: str
        """
        if bc_id is None:
            raise ValueError("Invalid value for `bc_id`, must not be `None`")  # noqa: E501

        self._bc_id = bc_id

    @property
    def user_id(self):
        """Gets the user_id of this AssetUnassignBody.  # noqa: E501


        :return: The user_id of this AssetUnassignBody.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this AssetUnassignBody.


        :param user_id: The user_id of this AssetUnassignBody.  # noqa: E501
        :type: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssetUnassignBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssetUnassignBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
