# coding: utf-8

"""
 Copyright 2023 TikTok Pte. Ltd.

 This source code is licensed under the MIT license found in
 the LICENSE file in the root directory of this source tree.
"""
import pprint
import re  # noqa: F401

import six

class CampaigngmvMaxcreatePromotionDaysCustomScheduleList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'end_date': 'str',
        'schedule_type': 'str',
        'start_date': 'str'
    }

    attribute_map = {
        'end_date': 'end_date',
        'schedule_type': 'schedule_type',
        'start_date': 'start_date'
    }

    def __init__(self, end_date=None, schedule_type='STARTEND', start_date=None):  # noqa: E501
        """CampaigngmvMaxcreatePromotionDaysCustomScheduleList - a model defined in Swagger"""  # noqa: E501
        self._end_date = None
        self._schedule_type = None
        self._start_date = None
        self.discriminator = None
        self.end_date = end_date
        if schedule_type is not None:
            self.schedule_type = schedule_type
        self.start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this CampaigngmvMaxcreatePromotionDaysCustomScheduleList.  # noqa: E501


        :return: The end_date of this CampaigngmvMaxcreatePromotionDaysCustomScheduleList.  # noqa: E501
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this CampaigngmvMaxcreatePromotionDaysCustomScheduleList.


        :param end_date: The end_date of this CampaigngmvMaxcreatePromotionDaysCustomScheduleList.  # noqa: E501
        :type: str
        """
        if end_date is None:
            raise ValueError("Invalid value for `end_date`, must not be `None`")  # noqa: E501

        self._end_date = end_date

    @property
    def schedule_type(self):
        """Gets the schedule_type of this CampaigngmvMaxcreatePromotionDaysCustomScheduleList.  # noqa: E501


        :return: The schedule_type of this CampaigngmvMaxcreatePromotionDaysCustomScheduleList.  # noqa: E501
        :rtype: str
        """
        return self._schedule_type

    @schedule_type.setter
    def schedule_type(self, schedule_type):
        """Sets the schedule_type of this CampaigngmvMaxcreatePromotionDaysCustomScheduleList.


        :param schedule_type: The schedule_type of this CampaigngmvMaxcreatePromotionDaysCustomScheduleList.  # noqa: E501
        :type: str
        """

        self._schedule_type = schedule_type

    @property
    def start_date(self):
        """Gets the start_date of this CampaigngmvMaxcreatePromotionDaysCustomScheduleList.  # noqa: E501


        :return: The start_date of this CampaigngmvMaxcreatePromotionDaysCustomScheduleList.  # noqa: E501
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this CampaigngmvMaxcreatePromotionDaysCustomScheduleList.


        :param start_date: The start_date of this CampaigngmvMaxcreatePromotionDaysCustomScheduleList.  # noqa: E501
        :type: str
        """
        if start_date is None:
            raise ValueError("Invalid value for `start_date`, must not be `None`")  # noqa: E501

        self._start_date = start_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CampaigngmvMaxcreatePromotionDaysCustomScheduleList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CampaigngmvMaxcreatePromotionDaysCustomScheduleList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
