# coding: utf-8

"""
 Copyright 2023 TikTok Pte. Ltd.

 This source code is licensed under the MIT license found in
 the LICENSE file in the root directory of this source tree.
"""
import pprint
import re  # noqa: F401

import six

class FilteringAdGet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ad_ids': 'list[str]',
        'ad_name': 'str',
        'adgroup_ids': 'list[str]',
        'buying_types': 'list[str]',
        'campaign_ids': 'list[str]',
        'campaign_system_origins': 'list[str]',
        'creation_filter_end_time': 'str',
        'creation_filter_start_time': 'str',
        'creative_material_mode': 'str',
        'destination': 'str',
        'modified_after': 'str',
        'objective_type': 'str',
        'optimization_goal': 'str',
        'primary_status': 'str',
        'secondary_status': 'str'
    }

    attribute_map = {
        'ad_ids': 'ad_ids',
        'ad_name': 'ad_name',
        'adgroup_ids': 'adgroup_ids',
        'buying_types': 'buying_types',
        'campaign_ids': 'campaign_ids',
        'campaign_system_origins': 'campaign_system_origins',
        'creation_filter_end_time': 'creation_filter_end_time',
        'creation_filter_start_time': 'creation_filter_start_time',
        'creative_material_mode': 'creative_material_mode',
        'destination': 'destination',
        'modified_after': 'modified_after',
        'objective_type': 'objective_type',
        'optimization_goal': 'optimization_goal',
        'primary_status': 'primary_status',
        'secondary_status': 'secondary_status'
    }

    def __init__(self, ad_ids=None, ad_name=None, adgroup_ids=None, buying_types=None, campaign_ids=None, campaign_system_origins=None, creation_filter_end_time=None, creation_filter_start_time=None, creative_material_mode=None, destination=None, modified_after=None, objective_type=None, optimization_goal=None, primary_status='STATUS_NOT_DELETE', secondary_status=None):  # noqa: E501
        """FilteringAdGet - a model defined in Swagger"""  # noqa: E501
        self._ad_ids = None
        self._ad_name = None
        self._adgroup_ids = None
        self._buying_types = None
        self._campaign_ids = None
        self._campaign_system_origins = None
        self._creation_filter_end_time = None
        self._creation_filter_start_time = None
        self._creative_material_mode = None
        self._destination = None
        self._modified_after = None
        self._objective_type = None
        self._optimization_goal = None
        self._primary_status = None
        self._secondary_status = None
        self.discriminator = None
        if ad_ids is not None:
            self.ad_ids = ad_ids
        if ad_name is not None:
            self.ad_name = ad_name
        if adgroup_ids is not None:
            self.adgroup_ids = adgroup_ids
        if buying_types is not None:
            self.buying_types = buying_types
        if campaign_ids is not None:
            self.campaign_ids = campaign_ids
        if campaign_system_origins is not None:
            self.campaign_system_origins = campaign_system_origins
        if creation_filter_end_time is not None:
            self.creation_filter_end_time = creation_filter_end_time
        if creation_filter_start_time is not None:
            self.creation_filter_start_time = creation_filter_start_time
        if creative_material_mode is not None:
            self.creative_material_mode = creative_material_mode
        if destination is not None:
            self.destination = destination
        if modified_after is not None:
            self.modified_after = modified_after
        if objective_type is not None:
            self.objective_type = objective_type
        if optimization_goal is not None:
            self.optimization_goal = optimization_goal
        if primary_status is not None:
            self.primary_status = primary_status
        if secondary_status is not None:
            self.secondary_status = secondary_status

    @property
    def ad_ids(self):
        """Gets the ad_ids of this FilteringAdGet.  # noqa: E501


        :return: The ad_ids of this FilteringAdGet.  # noqa: E501
        :rtype: list[str]
        """
        return self._ad_ids

    @ad_ids.setter
    def ad_ids(self, ad_ids):
        """Sets the ad_ids of this FilteringAdGet.


        :param ad_ids: The ad_ids of this FilteringAdGet.  # noqa: E501
        :type: list[str]
        """

        self._ad_ids = ad_ids

    @property
    def ad_name(self):
        """Gets the ad_name of this FilteringAdGet.  # noqa: E501


        :return: The ad_name of this FilteringAdGet.  # noqa: E501
        :rtype: str
        """
        return self._ad_name

    @ad_name.setter
    def ad_name(self, ad_name):
        """Sets the ad_name of this FilteringAdGet.


        :param ad_name: The ad_name of this FilteringAdGet.  # noqa: E501
        :type: str
        """

        self._ad_name = ad_name

    @property
    def adgroup_ids(self):
        """Gets the adgroup_ids of this FilteringAdGet.  # noqa: E501


        :return: The adgroup_ids of this FilteringAdGet.  # noqa: E501
        :rtype: list[str]
        """
        return self._adgroup_ids

    @adgroup_ids.setter
    def adgroup_ids(self, adgroup_ids):
        """Sets the adgroup_ids of this FilteringAdGet.


        :param adgroup_ids: The adgroup_ids of this FilteringAdGet.  # noqa: E501
        :type: list[str]
        """

        self._adgroup_ids = adgroup_ids

    @property
    def buying_types(self):
        """Gets the buying_types of this FilteringAdGet.  # noqa: E501


        :return: The buying_types of this FilteringAdGet.  # noqa: E501
        :rtype: list[str]
        """
        return self._buying_types

    @buying_types.setter
    def buying_types(self, buying_types):
        """Sets the buying_types of this FilteringAdGet.


        :param buying_types: The buying_types of this FilteringAdGet.  # noqa: E501
        :type: list[str]
        """

        self._buying_types = buying_types

    @property
    def campaign_ids(self):
        """Gets the campaign_ids of this FilteringAdGet.  # noqa: E501


        :return: The campaign_ids of this FilteringAdGet.  # noqa: E501
        :rtype: list[str]
        """
        return self._campaign_ids

    @campaign_ids.setter
    def campaign_ids(self, campaign_ids):
        """Sets the campaign_ids of this FilteringAdGet.


        :param campaign_ids: The campaign_ids of this FilteringAdGet.  # noqa: E501
        :type: list[str]
        """

        self._campaign_ids = campaign_ids

    @property
    def campaign_system_origins(self):
        """Gets the campaign_system_origins of this FilteringAdGet.  # noqa: E501


        :return: The campaign_system_origins of this FilteringAdGet.  # noqa: E501
        :rtype: list[str]
        """
        return self._campaign_system_origins

    @campaign_system_origins.setter
    def campaign_system_origins(self, campaign_system_origins):
        """Sets the campaign_system_origins of this FilteringAdGet.


        :param campaign_system_origins: The campaign_system_origins of this FilteringAdGet.  # noqa: E501
        :type: list[str]
        """

        self._campaign_system_origins = campaign_system_origins

    @property
    def creation_filter_end_time(self):
        """Gets the creation_filter_end_time of this FilteringAdGet.  # noqa: E501


        :return: The creation_filter_end_time of this FilteringAdGet.  # noqa: E501
        :rtype: str
        """
        return self._creation_filter_end_time

    @creation_filter_end_time.setter
    def creation_filter_end_time(self, creation_filter_end_time):
        """Sets the creation_filter_end_time of this FilteringAdGet.


        :param creation_filter_end_time: The creation_filter_end_time of this FilteringAdGet.  # noqa: E501
        :type: str
        """

        self._creation_filter_end_time = creation_filter_end_time

    @property
    def creation_filter_start_time(self):
        """Gets the creation_filter_start_time of this FilteringAdGet.  # noqa: E501


        :return: The creation_filter_start_time of this FilteringAdGet.  # noqa: E501
        :rtype: str
        """
        return self._creation_filter_start_time

    @creation_filter_start_time.setter
    def creation_filter_start_time(self, creation_filter_start_time):
        """Sets the creation_filter_start_time of this FilteringAdGet.


        :param creation_filter_start_time: The creation_filter_start_time of this FilteringAdGet.  # noqa: E501
        :type: str
        """

        self._creation_filter_start_time = creation_filter_start_time

    @property
    def creative_material_mode(self):
        """Gets the creative_material_mode of this FilteringAdGet.  # noqa: E501


        :return: The creative_material_mode of this FilteringAdGet.  # noqa: E501
        :rtype: str
        """
        return self._creative_material_mode

    @creative_material_mode.setter
    def creative_material_mode(self, creative_material_mode):
        """Sets the creative_material_mode of this FilteringAdGet.


        :param creative_material_mode: The creative_material_mode of this FilteringAdGet.  # noqa: E501
        :type: str
        """

        self._creative_material_mode = creative_material_mode

    @property
    def destination(self):
        """Gets the destination of this FilteringAdGet.  # noqa: E501


        :return: The destination of this FilteringAdGet.  # noqa: E501
        :rtype: str
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this FilteringAdGet.


        :param destination: The destination of this FilteringAdGet.  # noqa: E501
        :type: str
        """

        self._destination = destination

    @property
    def modified_after(self):
        """Gets the modified_after of this FilteringAdGet.  # noqa: E501


        :return: The modified_after of this FilteringAdGet.  # noqa: E501
        :rtype: str
        """
        return self._modified_after

    @modified_after.setter
    def modified_after(self, modified_after):
        """Sets the modified_after of this FilteringAdGet.


        :param modified_after: The modified_after of this FilteringAdGet.  # noqa: E501
        :type: str
        """

        self._modified_after = modified_after

    @property
    def objective_type(self):
        """Gets the objective_type of this FilteringAdGet.  # noqa: E501


        :return: The objective_type of this FilteringAdGet.  # noqa: E501
        :rtype: str
        """
        return self._objective_type

    @objective_type.setter
    def objective_type(self, objective_type):
        """Sets the objective_type of this FilteringAdGet.


        :param objective_type: The objective_type of this FilteringAdGet.  # noqa: E501
        :type: str
        """

        self._objective_type = objective_type

    @property
    def optimization_goal(self):
        """Gets the optimization_goal of this FilteringAdGet.  # noqa: E501


        :return: The optimization_goal of this FilteringAdGet.  # noqa: E501
        :rtype: str
        """
        return self._optimization_goal

    @optimization_goal.setter
    def optimization_goal(self, optimization_goal):
        """Sets the optimization_goal of this FilteringAdGet.


        :param optimization_goal: The optimization_goal of this FilteringAdGet.  # noqa: E501
        :type: str
        """

        self._optimization_goal = optimization_goal

    @property
    def primary_status(self):
        """Gets the primary_status of this FilteringAdGet.  # noqa: E501


        :return: The primary_status of this FilteringAdGet.  # noqa: E501
        :rtype: str
        """
        return self._primary_status

    @primary_status.setter
    def primary_status(self, primary_status):
        """Sets the primary_status of this FilteringAdGet.


        :param primary_status: The primary_status of this FilteringAdGet.  # noqa: E501
        :type: str
        """

        self._primary_status = primary_status

    @property
    def secondary_status(self):
        """Gets the secondary_status of this FilteringAdGet.  # noqa: E501


        :return: The secondary_status of this FilteringAdGet.  # noqa: E501
        :rtype: str
        """
        return self._secondary_status

    @secondary_status.setter
    def secondary_status(self, secondary_status):
        """Sets the secondary_status of this FilteringAdGet.


        :param secondary_status: The secondary_status of this FilteringAdGet.  # noqa: E501
        :type: str
        """

        self._secondary_status = secondary_status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FilteringAdGet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FilteringAdGet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
