# coding: utf-8

"""
 Copyright 2023 TikTok Pte. Ltd.

 This source code is licensed under the MIT license found in
 the LICENSE file in the root directory of this source tree.
"""
import pprint
import re  # noqa: F401

import six

class OptimizerRuleCreateBodyNotification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email_setting': 'OptimizerRuleCreateBodyNotificationEmailSetting',
        'notification_type': 'str'
    }

    attribute_map = {
        'email_setting': 'email_setting',
        'notification_type': 'notification_type'
    }

    def __init__(self, email_setting=None, notification_type=None):  # noqa: E501
        """OptimizerRuleCreateBodyNotification - a model defined in Swagger"""  # noqa: E501
        self._email_setting = None
        self._notification_type = None
        self.discriminator = None
        if email_setting is not None:
            self.email_setting = email_setting
        self.notification_type = notification_type

    @property
    def email_setting(self):
        """Gets the email_setting of this OptimizerRuleCreateBodyNotification.  # noqa: E501


        :return: The email_setting of this OptimizerRuleCreateBodyNotification.  # noqa: E501
        :rtype: OptimizerRuleCreateBodyNotificationEmailSetting
        """
        return self._email_setting

    @email_setting.setter
    def email_setting(self, email_setting):
        """Sets the email_setting of this OptimizerRuleCreateBodyNotification.


        :param email_setting: The email_setting of this OptimizerRuleCreateBodyNotification.  # noqa: E501
        :type: OptimizerRuleCreateBodyNotificationEmailSetting
        """

        self._email_setting = email_setting

    @property
    def notification_type(self):
        """Gets the notification_type of this OptimizerRuleCreateBodyNotification.  # noqa: E501


        :return: The notification_type of this OptimizerRuleCreateBodyNotification.  # noqa: E501
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type):
        """Sets the notification_type of this OptimizerRuleCreateBodyNotification.


        :param notification_type: The notification_type of this OptimizerRuleCreateBodyNotification.  # noqa: E501
        :type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OptimizerRuleCreateBodyNotification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OptimizerRuleCreateBodyNotification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
